# This rule is not used by the project kalypsoserving itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over serving.serving.kalypso.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kalypsoserving
    app.kubernetes.io/managed-by: kustomize
  name: kalypsoproject-admin-role
rules:
- apiGroups:
  - serving.serving.kalypso.io
  resources:
  - kalypsoprojects
  verbs:
  - '*'
- apiGroups:
  - serving.serving.kalypso.io
  resources:
  - kalypsoprojects/status
  verbs:
  - get
