# This rule is not used by the project kalypsoserving itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the serving.serving.kalypso.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kalypsoserving
    app.kubernetes.io/managed-by: kustomize
  name: kalypsotritonserver-editor-role
rules:
- apiGroups:
  - serving.serving.kalypso.io
  resources:
  - kalypsotritonservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - serving.serving.kalypso.io
  resources:
  - kalypsotritonservers/status
  verbs:
  - get
