## Append samples of your project ##
resources:
- serving_v1alpha1_kalypsoproject.yaml
- serving_v1alpha1_kalypsoapplication.yaml
- serving_v1alpha1_kalypsotritonserver.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
